In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
data=pd.read_csv('Churn_Modelling.csv')

In [4]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [5]:
data=data.drop(["RowNumber","CustomerId","Surname"], axis=1)

In [6]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])

In [8]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
onehot_encoder_geo = OneHotEncoder(sparse_output=False)

In [11]:
geo_encoder=onehot_encoder_geo.fit_transform(data[["Geography"]])

In [12]:
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [13]:
onehot_encoder_geo.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [14]:
geo_encoder_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out())

In [15]:
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [16]:
data=pd.concat([data.drop("Geography",axis=1),geo_encoder_df],axis=1)

In [17]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [18]:
import joblib


# joblib.dump(onehot_encoder_geo, "geo_encoder.pkl")
# joblib.dump(label_encoder_gender, "gender_encoder.pkl")

In [19]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [20]:
X=data.drop("Exited",axis=1)
y=data["Exited"]

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

sacaler=StandardScaler()
X_train=sacaler.fit_transform(X_train)
X_test=sacaler.transform(X_test)

In [22]:
# joblib.dump(sacaler, "scaler.pkl")

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [24]:
model=Sequential([
    Dense(64,activation="relu",input_shape=(X_train.shape[1],)),
    Dense(32,activation="relu"),
    Dense(1,activation="sigmoid")
])

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [26]:
import tensorflow as tf

In [27]:
import tensorflow as tf
opt=tf.keras.optimizers.Adam(learning_rate=0.001)
loss=tf.keras.losses.BinaryCrossentropy()
loss

In [28]:
model.compile(optimizer=opt,loss=loss,metrics=["accuracy"])

In [29]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir="log/fit" +datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [30]:
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=5,restore_best_weights=True)

In [31]:
history=model.fit(
     
     X_train,y_train,validation_data=(X_test,y_test),epochs=100,
        callbacks=[early_stopping_callback,tensorflow_callback]
)

Epoch 1/100
250/250 [==============================] - 3s 5ms/step - loss: 0.4515 - accuracy: 0.8043 - val_loss: 0.3968 - val_accuracy: 0.8295
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3861 - accuracy: 0.8403 - val_loss: 0.3616 - val_accuracy: 0.8485
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3539 - accuracy: 0.8589 - val_loss: 0.3510 - val_accuracy: 0.8545
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3444 - accuracy: 0.8587 - val_loss: 0.3467 - val_accuracy: 0.8585
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3403 - accuracy: 0.8576 - val_loss: 0.3535 - val_accuracy: 0.8525
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3372 - accuracy: 0.8597 - val_loss: 0.3447 - val_accuracy: 0.8505
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3347 - accuracy: 0.8629 - val_loss: 0.3426 - val_accuracy: 0.8585
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3313 - accuracy: 0.8614 - val_loss: 0.3474 - val_accuracy: 0.8570
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3289 - accuracy: 0.8649 - val_loss: 0.3428 - val_accuracy: 0.8560
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3260 - accuracy: 0.8649 - val_loss: 0.3418 - val_accuracy: 0.8580
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3257 - accuracy: 0.8636 - val_loss: 0.3399 - val_accuracy: 0.8620
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3237 - accuracy: 0.8654 - val_loss: 0.3398 - val_accuracy: 0.8600
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3223 - accuracy: 0.8665 - val_loss: 0.3423 - val_accuracy: 0.8590
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3208 - accuracy: 0.8670 - val_loss: 0.3641 - val_accuracy: 0.8520
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3192 - accuracy: 0.8681 - val_loss: 0.3390 - val_accuracy: 0.8610
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3174 - accuracy: 0.8686 - val_loss: 0.3411 - val_accuracy: 0.8620
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3168 - accuracy: 0.8683 - val_loss: 0.3405 - val_accuracy: 0.8600
Epoch 18/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3143 - accuracy: 0.8717 - val_loss: 0.3420 - val_accuracy: 0.8630
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3132 - accuracy: 0.8706 - val_loss: 0.3415 - val_accuracy: 0.8675
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3112 - accuracy: 0.8725 - val_loss: 0.3404 - val_accuracy: 0.8645

In [32]:
model.save("model.h5")

d:\udemy ai\deep learning\ann\annclassification\ann\venv\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [33]:
%load_ext tensorboard

In [36]:
%tensorboard --logdir log/fit20260604-174103

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "D:\udemy ai\deep learning\ann\annclassification\ann\venv\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\udemy ai\deep learning\ann\annclassification\ann\venv\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "d:\udemy ai\deep learning\ann\annclassification\ann\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "D:\udemy ai\deep learning\ann\annclassification\ann\venv\lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "D:\udemy ai\deep learning\ann\annclassification\ann\venv\lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'