In [78]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [79]:
model = load_model("model.h5")

In [80]:
import joblib

scaler = joblib.load("scaler.pkl")

geo_encoder = joblib.load("geo_encoder.pkl")

gender_encoder = joblib.load("gender_encoder.pkl")

In [81]:
input_data={
    "CreditScore": [600],
    "Geography": ["France"],
    "Gender": ["Male"],                          
    "Age": [40],
    "Tenure": [3],
    "Balance": [60000],
    "NumOfProducts": [2],
    "HasCrCard": [1],
    "IsActiveMember": [1],
    "EstimatedSalary": [50000]

}

In [82]:
input_df = pd.DataFrame(input_data)

In [83]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [84]:
geo_encoded = geo_encoder.transform(input_df[["Geography"]])
gender_encoded=gender_encoder.transform(input_df[["Gender"]])

d:\udemy ai\deep learning\ann\annclassification\ann\venv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [85]:
gender_encoded
geo_encoded

array([[1., 0., 0.]])

In [86]:
geo_encoder.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [87]:
geo_encoded_df=pd.DataFrame(geo_encoded,columns=geo_encoder.get_feature_names_out(["Geography"]))

In [88]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [89]:
input_df=pd.concat([input_df.drop(["Geography"],axis=1),geo_encoded_df],axis=1)

In [90]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [91]:
input_df.loc[0, "Gender"] =gender_encoded[0]

In [92]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [93]:
input_scaled=scaler.transform(input_df)

In [94]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [95]:
# prediction

In [97]:
prediction=model.predict(input_scaled)

1/1 [==============================] - 0s 20ms/step

In [101]:
prediction=prediction[0][0]

In [102]:
if prediction>0.5:
    print("The customer is likely to leave the bank.")  
else:  
     print("The customer is likely to stay with the bank.")

The customer is likely to stay with the bank.